language: objective-c
osx_image: xcode12.2
env:
- LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
before_install:
- pod repo update
script:
- pod spec lint --allow-warnings
notifications:
  slack:
    secure: p8pcIrndTPBievnLLSv51nSwIHHHqDgMgapE7Q9T2jV5QUk4dEDmP8gYih8yKfh2tUb9oI5JrMxHbmxoV9juRyW08BpD8RQVEOYU1gTUoH0r6HVoM6YXhEvcCB17GbRjlfcxyxr11eee1WQ67w0WixowMixjN+sKXtCAaoT8wRg=
